### ISSUE TITLE
有个小问题, 现在下载图片用的似乎不是软件上设置的代理服务器

### ISSUE THREAD

**Issue by fallmq** [lqs1848/DownloadWnacgByPhoto#4]
解析的时候用的是软件上配置的.
下载的时候用的似乎是系统的代理服务器.
我只在软件上配置代理, 可以解析, 但是在下载图片过程中会卡住; 配置完系统代理后才能正常下载.

**Comment by lqs1848** [comment]
之前都是用的 Http 去调用
后来下载改成用 WebClient 就忘记了这事
https://github.com/lqs1848/DownloadWnacgByPhoto/releases/download/1.08/wnacg.zip
